TUNE=peak
EXT=v8plus



LDFLAGS = -Bstatic -fast -xarch=v8plus
CFLAGS = -Bstatic  -fast -xarch=v8plus

LDFLAGS =  -O3 -mcpu=v8
CFLAGS =   -O3 -mcpu=v8

LDFLAGS = -fast
CFLAGS = -fast

BENCHLANG        = C
CC = /home/faculty/koppel/pub/sbuild/gcc-test/home/sol/bin/gcc
CC = /home/sol/gcc/bin/gcc
CC               = ${SPECLANG}/cc
CXX              = ${SPECLANG}/CC 
F77              = ${SPECLANG}/f77
FC               = ${SPECLANG}/f90
Issue            = 
OS               = sunos
Page             = 
SPECLANG         = /local/SUNWspro/bin
USE_VPATH        = 0
VENDOR           = Sun Microsystems
VPATH_CINCLUDE   = 
VPATH_CXXINCLUDE = 
VPATH_F90INCLUDE = 
VPATH_FINCLUDE   = 
VPATH_INCLUDE    = 
Volume           = 
abstol           = 6
action           = validate
backup_config    = 1
baseexe          = mesa
basepeak         = 0
benchdir         = benchspec
benchmark        = 177.mesa
bindir           = exe
changedmd5       = 0
check_md5        = 1
command_add_redirect = 0
commanderrfile   = speccmds.err
commandexe       = mesa_peak.v8plus
commandfile      = speccmds.cmd
commandoutfile   = speccmds.out
company_name     = Sun Microsystems
compareerrfile   = compare.err
comparefile      = compare.cmd
compareoutfile   = compare.out
compile_error    = 0
compwhite        = 
configdir        = config
configpath       = /home/faculty/koppel/pub/bm/spec2000/config/sun_sparc_solaris.cfg
datadir          = data
deletebinaries   = 0
deletework       = 0
difflines        = 10
dirprot          = 511
endian           = 4321
env_vars         = 0
exitvals         = spec_exit
expand_notes     = 0
ext              = v8plus
fast_rundir_verify = 0
feedback         = 1
fileprot         = 511
help             = 0
hw_avail         = 
hw_cpu           = UltraSPARC-xxx
hw_cpu_mhz       = xxx MHz
hw_disk          = 
hw_disk1         = 
hw_fpu           = Integrated
hw_memory        = 
hw_model         = xxx
hw_ncpu          = 1
hw_ncpuorder     = x
hw_ocache        = None
hw_other1        = 
hw_parallel      = None
hw_pcache        = xxKBI+xxKBD on chip
hw_scache        = xxMB(I+D) off chip
hw_tcache        = None
hw_vendor        = Sun Microsystems
ignore_errors    = 0
ignore_sigint    = 0
inputdir         = input
iterations       = 3
license_num      = 6
line_width       = 0
locking          = 1
log              = log
log_line_width   = 0
lognum           = 038
mach             = default
machine_name     = 
make             = specmake
make_no_clobber  = 0
makeflags        = 
max_active_compares = 0
max_users        = 1
mean_anyway      = 0
min_report_runs  = 3
minimize_builddirs = 0
minimize_rundirs = 0
name             = mesa
nc               = 0
notes00          =   
notes01          =  Portability: 178.galgel: -e -fixed
notes02          =   
notes03          =  C   flags: -fast -xcrossfile -xprofile
notes04          =  F90 flags: -fast -xcrossfile -xprofile
num              = 177
obiwan           = 1
os_exe_ext       = 
output           = asc
output_format    = all
outputdir        = output
path             = /home/faculty/koppel/pub/bm/spec2000/benchspec/CFP2000/177.mesa
prefix           = 
rate             = 0
rawfile          = 
rawformat        = 0
rebuild          = 0
ref_tree_level   = Top level Config
reftime          = reftime
reltol           = 
reportable       = 0
resultdir        = result
run              = all
safe_eval        = 1
setprocgroup     = 1
sigint           = 2
size             = ref
skiptol          = 6
smarttune        = peak
specdiff         = specdiff
specmake         = Makefile.spec
specrun          = specinvoke
srcalt           = 
srcdir           = src
subworkdir       = work
sw_Kernel_Extensions = none
sw_avail         = 
sw_compiler      = Forte Developer 6 update 1
sw_compiler1     = 
sw_file          = UFS
sw_os            = Solaris 8
sw_other         = 
sw_state         = 
table            = 1
teeout           = 0
teerunout        = 0
test_date        = 
tester_name      = Sun Microsystems, Palo Alto
top              = /home/faculty/koppel/pub/bm/spec2000
tune             = peak
uid              = 2010
unbuffer         = 0
use_submit_for_speed = 0
username         = koppel
users            = 1
vendor           = anon
vendor_makefiles = 0
verbose          = 5
version          = 0
workdir          = run
worklist         = list
